name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Build the Docker image
      run: docker build . -t masterkube/axon:1.0
      
    - name: Docker Push
      run: docker push masterkube/axon:1.0
      
    - name: Perform Scan
      run: |
        docker save -o axon.tar masterkube/axon:1.0
        docker run --rm -e "WORKSPACE=${PWD}" -v $PWD:/app shiftleft/scan scan --src /app/axon.tar -o /app/reports --type docker
    
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: /app/reports
      
